dist: xenial
language: cpp
sudo: true

git:
  depth: 1
  quiet: true

notifications:
  email: false

os:
- linux

env:
- LUA=5.1
- LUA=5.2
- LUA=5.3

before_script:
- sudo apt install -y liblua${LUA}-dev
- mkdir build
- cd build

script:
- cmake ..
- make -j $(nproc || echo 4)

addons:
  apt:
    packages:
    - libeigen3-dev
    - libglew-dev
    - libtheora-dev
    - libjpeg-dev
    - libpng-dev
    - libglu1-mesa-dev
    - qtbase5-dev
    - qtbase5-dev-tools
    - libqt5opengl5-dev
