trigger:
- main

strategy:
  matrix:
    Linux:
      imageName: 'ubuntu-latest'
    Mac:
      imageName: 'macos-latest'
    Win:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- checkout: self

- bash:  echo "##vso[task.setvariable variable=shellopts]errexit"
  displayName: "Force exit on error (bash)"
  condition: not( eq( variables['Agent.OS'], 'Windows_NT' ) )

- script: |
    sudo apt update
    sudo apt install -y libeigen3-dev \
                        libepoxy-dev \
                        libavcodec-dev \
                        libavformat-dev \
                        libavutil-dev \
                        libswscale-dev \
                        libjpeg-dev \
                        libpng-dev \
                        libglu1-mesa-dev \
                        qtbase5-dev \
                        qtbase5-dev-tools \
                        libqt5opengl5-dev \
                        libgtk2.0-dev \
                        libgtkglext1-dev \
                        libfreetype6-dev \
                        libsdl2-dev \
                        libluajit-5.1-dev \
                        libfmt-dev
  displayName: 'Install Linux dependencies'
  condition: eq( variables['Agent.OS'], 'Linux' )

- script: |
    brew install pkg-config \
                 eigen \
                 ffmpeg \
                 gtk+ \
                 gtkglext \
                 cspice \
                 fmt \
                 jpeg \
                 gettext \
                 libpng \
                 lua \
                 qt5 \
                 freetype \
                 libepoxy \
                 sdl2
    brew link gettext --force
    brew link lua --force
  displayName: 'Install macOS dependencies'
  condition: eq( variables['Agent.OS'], 'Darwin' )

- script: |
    vcpkg --triplet=x86-windows install --recurse libpng libjpeg-turbo gettext luajit fmt libepoxy eigen3 freetype cspice
  displayName: 'Install Windows dependencies'
  condition: eq( variables['Agent.OS'], 'Windows_NT' )

- script: |
    mkdir build
    cd build
    cmake -DENABLE_SPICE=ON -DENABLE_TOOLS=ON -DENABLE_TESTS=ON -DENABLE_SDL=ON -DENABLE_GTK=ON -DENABLE_FFMPEG=ON -DENABLE_DATA=OFF ..
    make -j $(nproc || echo 4)
    CTEST_OUTPUT_ON_FAILURE=1 ctest
  workingDirectory: "$(system.defaultworkingdirectory)"
  displayName: "Build and test on GNU/Linux and macOS"
  condition: not( eq( variables['Agent.OS'], 'Windows_NT' ) )

- script: |
    @rem call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86
    mkdir build
    cd build
    cmake -DCMAKE_FIND_DEBUG_MODE=ON -DCMAKE_TOOLCHAIN_FILE=c:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x86-windows -DENABLE_SPICE=ON -DENABLE_TOOLS=ON -DENABLE_TESTS=ON -DENABLE_SDL=OFF -DENABLE_QT=OFF -DENABLE_DATA=OFF ..
    type CMakeFiles\CMakeOutput.log
    type CMakeFiles\CMakeError.log
    type CMakeCache.txt

    cmake --build . --config RelWithDebInfo -- /maxcpucount:4 /nologo
    set CTEST_OUTPUT_ON_FAILURE=1
    copy src\celestia\RelWithDebInfo\*.dll test\unit\RelWithDebInfo\
    ctest -C RelWithDebInfo
  workingDirectory: "$(system.defaultworkingdirectory)"
  displayName: "Build and test on Windows"
  condition: eq( variables['Agent.OS'], 'Windows_NT' )

- powershell: |
    cd c:/vcpkg/installed
    Get-ChildItem -Recurse
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
