name: Celestia

on:
  push:
    branches: [ master ]
    paths: [ src/**, test/**, .github/workflows/ci.yml, CMakeLists.txt ]
  pull_request:
    branches: [ master ]
    paths: [ src/**, test/**, .github/workflows/ci.yml, CMakeLists.txt ]

env:
  BUILD_TYPE: RelWithDebInfo
  CTEST_OUTPUT_ON_FAILURE: 1
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'

jobs:
  build-windows:
    name: "windows-${{matrix.platform}} with ${{matrix.qtversion}}"
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [ x86 ]
        qtversion: [ Qt5 ]

    steps:
    - name: 'Checkout source code'
      uses: actions/checkout@v3
      with:
        submodules: false

    - name: debug crap
      run: |
        Get-Childitem –Path C:\ -Include vcvarsall.bat,link.exe,rc.exe

    - name: Translate UI
      shell: cmd
      run: |
        dir 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise'
        dir 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat'
        call 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat' ${{matrix.platform}}
        md ${{github.workspace}}\build
        md ${{github.workspace}}\build\src
        md ${{github.workspace}}\build\src\celestia
        md ${{github.workspace}}\build\src\celestia\win32
        perl translate_resources.pl ${{matrix.platform}}
      working-directory: ${{github.workspace}}/po

    - name: Package artifacts
      working-directory: ${{github.workspace}}/build/src/celestia
      run: |
        7z a celestia-win.${{matrix.platform}}.7z win32\${{env.BUILD_TYPE}}\* win32\res\${{env.BUILD_TYPE}}\res_*.dll win32\res\res_*.dll

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: celestia-${{matrix.platform}}
        path: ${{github.workspace}}/build/src/*/*.7z
